name: Docker build rspamd
on:
  push:
    tags:
      - 'rspamd-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | sed 's/refs\/tags\/rspamd-v//')
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker-images/rspamd
          file: ./docker-images/rspamd/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nodemailer/rspamd:latest,nodemailer/rspamd:${{steps.get_version.outputs.VERSION}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}