name: Docker build haraka
on:
  push:
    tags:
      - 'haraka-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  main:
    runs-on: self-hosted
    steps:
      - 
        name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | sed 's/refs\/tags\/haraka-v//')
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker-images/haraka
          file: ./docker-images/haraka/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: nodemailer/haraka-wildduck:latest,nodemailer/haraka-wildduck:${{steps.get_version.outputs.VERSION}}
          build-args: |
            version=${{steps.get_version.outputs.VERSION}}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
